name: Bug Report
description: |
  Report about something malfunctioning or not working.
title: "[Bug]: "
labels: ["Bug"]
assignees:
  - HU-Lee
body:
  - type: checkboxes
    attributes:
      label: WARNING
      description: |
        This template is about something malfunctioning or not working.
        (ex. site crash, server is not working, etc.)
        DO NOT USE THIS TEMPLATE TO REPORT CONTENT, OR REQUEST THE FEATURE. 
        You can use discussions instead.
      options:
        - label: I understand this and I want to report the bug
          required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: If you don't know, just leave it blank.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: |
        Add any related information.
        - Device info
        - OS
        - Browser
        - Reference
